---
title: "Hassan Hijazi"
format:
  html:
    css: styles.css
---

```{r echo = FALSE, warning=FALSE}
library(tinytex)
suppressPackageStartupMessages(library(icons))

```

<button onclick="window.open('https://hijazihassan.github.io/files/cv-2024.pdf', '_blank');" class="btn">
    <i class="fa fa-download"></i> 1-page CV
</button>


## Professional Experience

-   PhD Project (2021 - currently): Studying Perturbed Histone Acylations in Huntington's Disease by Proteomics
    -   EDyP Lab - CEA Grenoble/France

    -   [The aim of this project was to identify and quantify differentially abundant histone post-translational modifications (hPTMs) between WT and Huntington's disease mouse models. For this purpose, I extracted histones from testis and brain tissues and prepared them for MS analysis by derivitizing free amines on unmodified or monomethylated lysine side chains and on free N-termini as well. I did this in-gel and in-solution. I used Orbitrap mass spectrometers (QEx HF and Ascend) to acquire data in DDA and PRM mode, and I interrogated the data using Mascot for identification and Proline or Skyline for validation and quantification. I used to manually validate the MS/MS spectra to confirm identifications, especially for combinatorial hPTM patterns and isobaric peptides. I wrote R scripts to organize and visualize the results and ended up wrapping all the scripts in an R package, which accelerated data analysis and ensured reproducibility and transparency in reporting the results end-to-end, in addition to plots that allow you to have a look at the result and also for quality checks to spot anomalies immediately.]{style="font-size: 14px;"}\
-   6-month internship (2021): Impact of detergents on sequencing membrane proteins using MALDI-MS
    -   Institut de Biologie Structurale (IBS) - Grenoble/France

    -   [Detergents are known to interfere with the protein mass spectra reducing the resolution and mass accuracy of the fragment ions. Thus it is important to remove of as much detergent as possible just before MALDI sequencing. During this internship, I screened a variety of detergents (non-ionic and zwitterionic) and explored their differential effects on different soluble proteins. I then investigated an *E. coli* membrane receptor, FhuA, as a case study illustrating the sequencing profiles of FhuA solubilized by different detergents.]{style="font-size: 14px;"}

        \
-   6-month internship (2020): Ultradeep Sequence-Function Mapping of Prokaryotic Promoter Libraries
    -   Department of Biosystems Science and Engineering (D-BSSE) - ETH - Basel/Switzerland

    -   [Promoters are crucial for initiation of transcription and therefore regulation of gene expression. However, we still do not fully understand how a promoter sequence encodes its functional properties. This hampers the progress of synthetic biology and challenges its engineering discipline. To overcome this limitation, we adapted a recently developed DNA-based phenotyping approach (ultradeep Acquisition of Sequence-Phenotype Interrelations; uASPIre) to enable high throughout recording of prokaryotic promoters. We developed a double recombinase system that allows us to quantitatively measure sequence-function relationships of large promoter libraries with high temporal resolution. To better understand the underlying mechanisms, we further developed a computational model to predict expression and activity of Bxb1, one of the used recombinases.]{style="font-size: 14px;"}

## Publications

[Mind Your Spectra: Bullet Points to Validate the Identification of Isobaric Histone Peptidoforms]{style="font-weight: bold;"} [(under revision)]{style="color: red;"}

[**Hassan Hijazi**, Julie Manessier, Sabine Brugiere, Tina Ravnsborg, Marie Courçon, Ole N Jensen, Anne-Marie Hesse, Christophe Bruley, Delphine Pflieger]{style="font-size: 14px;"}

[Sequencing intact membrane proteins using MALDI mass spectrometry]{style="font-weight: bold;"}

[Edison Zhamungui Sánchez; **Hassan Hijazi**; Jana Haidar; Enrica Mecarelli; Elda Bauda; Isabelle Petit-Härtlein; Jean-Marie Teulon; Jean-Luc Pellequer; Elisabetta Boeri Erba]{style="font-size: 14px;"}

[Front. Anal. Sci., 13 July 2023]{style="font-weight: bold; font-size: 12px;"}

[DOI](https://www.frontiersin.org/journals/analytical-science/articles/10.3389/frans.2023.1124741/full){.btn .btn-outline-primary .btn role="button" data-toggle="tooltip" title="Read the article online"}

[Toehold switch based biosensors for sensing the highly trafficked rosewood *Dalbergia maritima*]{style="font-weight: bold;"}

[Paul Soudier, Daniel Rodriguez Pinzon, Tristan Reif-Trauttmansdorff, **Hassan Hijazi**, Maëva Cherrière, Cátia Goncalves Pereira, Doriane Blaise, Maxime Pispisa, Angelyne Saint-Julien, William Hamlet, Melissa Nguevo, Eva Gomes, Sophia Belkhelfa, Anna Niarakisc, Manish Kushwaha, Ioana Grigoras]{style="font-size: 14px;"}

[Synthetic and Systems Biotechnology 30 March 2022]{style="font-weight: bold; font-size: 12px;"}

[DOI](https://www.sciencedirect.com/science/article/pii/S2405805X22000278?via%3Dihub){.btn .btn-outline-primary .btn role="button" data-toggle="tooltip" title="Read the article online"}

## Education

-   **PhD in Chemical Biology** \[2021 - *currently*\[ \| University of Grenoble Alpes

-   **Master 2 in NanoBiology** \[2021\] \| University of Grenoble Alpes

-   **Master 2 in Systems and Synthetic Biology** \[2020\] \| University of Paris Saclay

-   **Master 1 in Animal Biology** \[2014\] \| Lebanese Univeristy

-   **BS in Life & Earth Sciences** \[2013\] \| Lebanese Univeristy

## Computational Skills

-   Programming languages: R{{< fa brands r-project >}} and Python{{< fa brands python >}}

    -   I have developed **'HistonePTM'**, an R package to facilitate histone PTM analysis (not made public yet but have a glance at the [vignette](https://hijazihassan.github.io/histonePTM.html)).

-   Graphics software: Inkscape

-   Writing: $\LaTeX$

## Languages

-   English (Fluent)

-   French (Intermediate)

-   Arabic (Native)

## Conferences

-   French Proteomics Society - Club-Jeunes (FPS-CJ)

    -   Bourdeaux \[Flash Talk\]\

-   Joint Meeting of Spanish, French, and Portuguese Proteomics Societies

    -   ProteoVilamoura - Portugal (2022) \[Flash talk\]
    -   ProteoAix - France (2023)\[Poster\]

-   Symposium "Signaling through Chromatin" - Grenoble (2023) \[Poster\]\

-   Mass Spectrometry and Proteomic Analysis (SMAP) conference - Lille - France (upcoming in 09/2024) \[Participation in a bioinformatics workshop\]\

-   HUPO - Germany (2024) \[Abstract accepted\]\

## Professional Activities

-   A Current member of French Proteomics Society - Club Jeunes ([FPS-CJ Bureau](http://clubjeunesfps.free.fr/bureau.html)).

-   A member of 2020 iGEM team of Paris Saclay - Evry ([Golden Medal Winner](https://2020.igem.org/Team:Evry_Paris-Saclay/Team))

-   Master 2 student supervision (2024) as part of the project "HD-EpiEnergy".

## Teaching Experience

-   **Introduction to Proteomics** lecture for master 1 students as part of 'DNA synthesis, analysis, omics, big data and biotechnology' module \[to be delivered on 13 October 2024\] \| University of Grenoble Alpes

-   **Introduction to Proteomics** lecture for master 2 students as part of 'High Through Biology' course \[to be delivered on the 3$^{rd}$ of November 2024\] \| University of Grenoble Alpes

-   **Math and Biology Teacher** \[2015 - 2019\] \| Accra Community School - Ghana

## Let's Connect!

Thanks for dropping by! Find me also on:

{{< fa brands linkedin >}} [LinkedIn](https://www.linkedin.com/in/hijaziihassan/) {{< fa brands orcid >}} [orcid](https://orcid.org/my-orcid?orcid=0000-0001-6408-1768) {{< fa brands x-twitter >}} [Twitter](https://x.com/HassanHejazi) {{< fa brands github >}} [GitHub](https://github.com/HijaziHassan)
